sugarlabs/www

_layouts/base.html

Google doesn't work with Wikipedia image, so i uploaded our own image instead

Removed wikipedia image from the Google Graph

---

_layouts/base.html

`<a>` tag is forbidden in `<head>` by HTML rules.

Removed link placed in `head` section what caused an error to appear

---

README.md

Not using `bundle exec` to serve the website could cause versioning errors, and using `bundle exec` is recommended by Jekyll. 
This should hopefully save some people new to Jekyll and the gem package manager some debugging time!

Update installation instructions to use bundle exec

---

about-us.html

Fixes #114 and #115 
Removed Dextrose, "Harmonic distribution" and "Replacing Textbooks" hyperlinks from about-us.html 
@quozl please review.

Fixes broken links in about-us.html

---

index.html

Immediate fix for #123 
Added proper margins to 'Social Help Page' button and added  'Join the Conversation' button. This button points towards the IAEP mailing list page.
screenshot->
@quozl please review!

Added 'Join the Conversation' button 

---

Gemfile.lock

There is a vulnerability reported in nokogiri and it is recommended to update to v 1.8.1
Gemfile.lock has been updated to:
nokogiri ~> 1.8.1
Not 100% sure how to test this.

suggested security update

---

press.html

As per Sean Daly's direct request, he would like his contact information removed from the Sugar Labs Press page, as he is no longer the PR contact. This is documented at http://lists.sugarlabs.org/archive/marketing/2018-March/thread.html

Remove out-of-date PR contact information

---

_includes/footer.html

As per discussion with SLOBs, this will be removed for now (no SLOB disagreement), and will likely stay that way unless someone volunteers to keep it current, and/or is officially appointed as marketing overseer.

Remove decrepit Press Resources link from footer

---

css/airspace.css

in reference to #145  which was partially fixed, now it has been fixed completely and the cursor is not activated on hovering over titles which are not linked to anything.

fixed footer cursor

---

index.html

This video is not of sufficient quality to be prominently displayed on the landing page of sugarlabs.org. The quality of the voiceover work is also very poor, and nearly uninteligible at many points.

Remove Sugar Labs Embedded Youtube Video

---

about-irc.html

There are a number of listed IRC channels here, some of which were wrong, some of which no longer exist, and have not for many, many moons. This is a first attempt at culling the list, and grouping the channels

remove non-existent IRC channels and re-order list

---

music-blocks.html
turtle-blocks-js.html

I have updated all TB and MB links which previously used to point to Walter's github repo - they now point to the respective sugarlabs repos.
I updated MB's description re contributions made by GCI and GSoC participants (I got this new data from https://github.com/sugarlabs/musicblocks/blob/master/README.md)
I also realised that Dr Larry Scripp's NEC link was deprecated and replaced it with what I presume to be an updated page of his [here](https://necmusic.edu/faculty/larry-scripp)

Updated links to point to Music Blocks and Turtle Blocks repos

---

about-us.html
index.html
more.html

We refer to Sugar as an open source platform, but whereas we use a GNU license, Free/Libre is a more accurate description.

free/libre != open source

---

css/airspace.css

The 'About Us' heading heading on the about us page is not vertically aligned properly inside the box, so giving a padding-top has resolved the issue. I have made the necessary changes in the code and now the heading looks fine.

Changes in 'About Us' headign on about us page.

---

README.md

Our visitors recently have made assumptions that have not been supported
by consensus.  Partly this is because the README for the repository
hasn't changed much since the 2017 GSOC project for changing the site
style.
Add a better introduction.

Add introduction to the README

---

LicenseInformation.txt
_includes/footer.html
_includes/nav.html
_layouts/base.html
about-irc.html
about-libre-software-culture.html
about-us.html
booting-soas.html
contact-us.html
css/airspace.css
css/bootstrap.css
index.html
inquiry.html
js/bootstrap.js
more.html
music-blocks.html
press.html
search.html
sugar-for-raspberry-pi.html
sugar-for-raspbian.html
turtle-blocks-js.html

Fixes: #316 
I Ported the site to Bootstrap 4 from 3, As shown in this [Video](https://drive.google.com/file/d/1D3lE0u0dzlAqftz8OtgPNa-yj8sxIPQy/view?usp=sharing), Using [this](https://getbootstrap.com/docs/4.0/migration/).
Process:
1.  I changed the old "bootstrap.css" and "bootstrap.js" of bootstrap 3 to 4 by using official [Documents](https://getbootstrap.com/docs/4.0/getting-started/download/).
2.  Changed the first-header in nav.html as its links and navbar-toggler were completely broken, and updated the collapse navbar-toggler with previously using hamburger navigation for mobile view.
3. Major change here is because **Flexbox is enabled by default** in the v4 version, so I used **class="d-flex justify-content-center"** for the required places.
4. Updated the version in the license …

Ported site to Bootstrap 4 from 3

---

_includes/footer.html
css/airspace.css

Fixes: #370 
As shown below:
* removed the 'position' style of footer icons in 'airspace.css' to stop overlapping.
* made footer div responsive by correcting classes in 'footer.html' icons div and aligned code lines correctly after the change (as div are removed).

Fixed the overlapping of 'footer icons'

---

Gemfile
Gemfile.lock
_includes/nav.html
css/airspace.css

1. In files Gemfile and Gemfile.lock, `webrick` dependency is added to avoid the 'require' error.
2. In `nav.html` file, the left CSS property is set to be a relative value of 25.2% to avoid overlapping with title and distance variable is removed wherever necessary.
3. In `airspace.css`, width of `searchForm` is reduced to 180px to resolve the issue of overlapping.

Fix search bar overlapping title. Fixes #375

---

music-blocks.html

Some links are dead; one is forwarding to a place we don't want it to forward.

Remove links (somewhat urgent)

---

css/airspace.css
sugar-stories.html

fixed: #458 
Tested on various screen sizes.
Here is the comparison of the updates:
The absence of margin-top: 80px was causing issues on screens with a width of 767px or less.

Updated Sugar Stories Layout

---

css/airspace.css

Summary
Fixes an issue where the Story1 and Reference buttons were not functioning between screen widths of 991px and 1214px.
Problem
The buttons in the /sugar-stories section did not respond to clicks when viewed on devices with a screen width between 991px and 1214px. This impacted the user experience as the buttons were not usable in this specific range.
Fix
Adjusted the z-index and position properties in the CSS:
Added z-index: 10;
Set position: relative;
This ensures the buttons now respond properly to clicks in the specified screen width range.
Fixes #465

Fixed #465 Story1 and Reference Button Non-Functional on Width 991px to 1214px

---

js/main.js
press.html

Fixes #456
There was an unnecessary loop in the JS file to limit the displayed press, since the HTML already has a loop for this purpose. I believe we should only use the HTML loop to limit the posts. I think this approach is much better.
@pikurasa What do you think about it ?

fix: remove redundant JS loop and limit press rendering to HTML

---

css/airspace.css
index.html

In the ‘By the Numbers’ section of the Sugar Labs website, the data was previously misaligned, with uneven spacing between numbers and text blocks. This made the section harder to read and reduced the visual appeal. I have adjusted the alignment and spacing for better readability and user interaction, ensuring the content is now more evenly distributed and aesthetically pleasing
After testing the changes on my local machine, I observed the alignment issue was fixed. Although it looked somewhat raw locally, updating it on the actual site will reflect the changes neatly and improve the user experience.

Fix alignment in the ‘By the Numbers’ section for better visual consistency

---

css/airspace.css

fix: responsive button design for download section

---

_layouts/base.html
css/airspace.css
music-blocks.html

In this I had linked the custom.css stylesheet in the website 
before:
after:

Linking the custom.css for the customized styling 

---

FAQ.html
_config.yml
_faqs/Q1-What-is-SugarLabs.md
_faqs/Q2-What-is-the-mission-of-SugarLabs.md
_faqs/Q3-What-is-the principles-that-guide-SugarLabs.md
_faqs/Q4-What-makes-Sugar-different-from-other-educational-software-platform.md
_faqs/Q5-Who-can-use-Sugar-and-how-do-they-benefits.md
_faqs/Q6-Are-there-any-platforms-where-Sugar-runs-on.md
_includes/nav.html
_layouts/base.html
css/airspace.css
js/custom.js
js/main.js
sitemap.txt

The page looks like this
Vedio:
https://github.com/user-attachments/assets/54265a4b-815d-456d-9dea-4ebad33e5c2d
I have taken the FAQs from https://wiki.sugarlabs.org/go/Sugar_Labs/FAQ
@pikurasa please review.

added FAQ page

---

css/ion_icon_customization.scss

`darken()` is a deprecated global built-in function. It uses a legacy method for color manipulation that lead to several deprecation warnings on the terminal at best, and can lead to inconsistent results at worst (see [what the sass documentation has to say about it](https://sass-lang.com/documentation/breaking-changes/import/)).
`color.adjust()` provides a more modern, flexible, and predictable approach to adjusting specific color properties and is the recommended approach by the official sass documentation.
I have replaced the deprecated `darken()` function with `color.adjust()` to have the exact same visual effect for the viewer as intended by the original design.

Fixed deprecated sass functions

---

_includes/nav.html

Fixes #545 
This is how it look like 
@quozl @pikurasa please review.

Fixes #545 text color of "about us" option and "news" option

---

css/custom.css

Enhance responsiveness and styling of service section with equal-sized boxes, centered content, and consistent spacing.
Icons in the service section were misaligned, and the spacing between elements was inconsistent. This led to a cluttered appearance and reduced responsiveness, impacting the user experience across different screen sizes.
Verified changes on a local Linux-based environment.

enhancement for service section

---

_includes/footer.html
css/custom.css

This PR updates the visibility behavior of the 'Back to Top' button. Instead of being only in the footer, the button now appears when the user scrolls down the page by 30%. This change improves the user experience by providing quicker access to the top of the page.

Float icon back to top

---

_layouts/post.html
community-news.html

This PR addresses issue #571 by adding the author's name below the title of blog posts. The author’s name is fetched from the front matter and displayed in the blog layout as "by Author Name."
- Added dynamic display for the author name in the blog post layout.
- The `author` field in the front matter is now rendered below the post title.
- Updated CSS classes for styling the author name and post date.
Closes #571
1. Add `author: "Author Name"` to the front matter of any blog post.
2. Verify that the author's name is correctly displayed below the post title.
This implementation improves post attribution by clearly displaying the author's name for each blog post.
Before:
After:

Added author name display to blog

---

_includes/donation_banner.html
css/custom.css

A floating button for the donation banner to ensure visibility when the current banner is not visible or partially obscured.
SugarLabs aims to raise $25K by this fall, and the current donation banner is visually effective. However, if a user closes the banner or scrolls down, the banner becomes hidden. This is particularly noticeable on mobile devices, where the site's "Donate" button is located within the hamburger menu, making it less accessible.
To address this, I have implemented a floating donation button. This button becomes visible when the user scrolls down and the current banner is no longer in view or when the user closes the banner. It ensures a persistent and accessible way to encourage donations at all times.

Float Donation Button to Enhance Banner Visibility

---

about-us.html
css/custom.css

This pull request addresses issues with the UL elements being right aligned due to left padding being applied in custom.css .
- Removed `padding: revert` which was causing unnecessary left padding and misalignment of ul elements.
**Before:**
**After:**
**Before(footer)**:
**After(footer)**:
- Due to the removal of padding: revert the padding was set to 0 again for all the ul elements, because of which **only** the placement section was broken so added px-5 padding to the section which fixed all the things.
**Before(with padding:revert)**:
**After(with px-5)**:
(remains the same)

Fixes #644, Removed unnecessary left padding on various UL elements

---

about-us.html
css/custom.css

- Improved UI design of the About section.
- Updated Google Summer of Code link to the direct GitHub URL.
- The previous link redirected to a wiki page, causing unnecessary extra steps for users.

Update About Section UI and Fix Google Summer of Code Link

---

_includes/nav.html
sitemap.txt

Updated the position of "Products" section from "Donate" dropdown to a separate item on navbar.
mobile:
@pikurasa what do you think.

Update the position of "Products" on nav
