sugarlabs/www

- index.html
It is also very tiring for eyes. Tested on myself and my friends.
> Please... navy blue is really ugly in this case.

- index.html
> Capitalize activities

- _includes/footer.html
In order to verify the facebook page, we need to have a confirmation number publicly listed on the homepage. This is my Google Voice, and once the fb page is verified, I'll remove it :)
> Update footer.html for Facebook auth

- STRUCTURE.md
> Add STRUCTURE.md

- _layouts/base.html
There were some few wrong links that should have been removed but i am just seeing it for the first time, after doing some research why how website is not on Google search yet.
> Updated the base

- search.html
The search was rectified. There was a problem in google search API.
> search is working

- _includes/nav.html
Made changes to nav.html which fixes issue #193
> Fixed issue - "Search fails on pages other than index.html"

- _includes/footer.html
Fix #80 . 
This commit adds smooth scroll to top animation using jQuery.
> Add Scroll to top animation

- _includes/nav.html
in the mobile version, the text in the navbar is hidden when the white bg conflicts with the white text color, fixed it by changing the color of the text to be blue, thereby also matching with the rest of navbar elements.
> Fixed Text disappearing in mobile version navbar

- google6c0d01bc1a53fa32.html
Added a second verification file to give Samson Goddy access to Google knowledge graph
> Google verification file

- _includes/nav.html
- css/airspace.css
I have added the box-shadow to navbar. As you scroll down the page the box-shadow appears under navbar. :)
> Added Box-shadow to navbar

- README.md
- _includes/footer.html
- css/airspace.css
- js/main.js
- it doesn't work at the moment, leading people astray,
- it isn't clear how to make it work.
Work in progress; there may be other things to remove or change.
Probably:
* fixes #218,
* fixes #261.
> Proposal: Remove Chat

- index.html
the topmost addition of "open source" looked crappy. This is a first attempt at a fix.
> update order of wording

- _includes/footer.html
This commit hides the non-functional newsletter for the time being i.e., the lines implementing the newsletter is commented out as decided in #249.
> Hide non-functional newsletter

- css/ion_icon_customization.scss
issue #293 
-Added box shadow
-Fixed border radius
> improved design of floating social buttons

- index.html
Remove alpha mention on Sugarizer, it's no longer an alpha product :-)
> Remove alpha mention on Sugarizer

- README.md
I was reading through and I discovered few typos ( some were explicitly obvious while the others weren't).
> Fixed some major typos

- README.md
- _posts/2009-12-08-L’association-à-but-non-lucratif-Sugar-Labs-annonce-la-version-2-de-“Sugar-on-a-Stick”
- booting-soas.html
Fixes: #360 
Changed Files:
- `readme.md`
- `booting-soas.html`
- `_posts/2009-12-08-L’association-à-but-non-lucratif-Sugar-Labs-annonce-la-version-2-de-“Sugar-on-a-Stick”`
> Updated 'Sugarlabs' to 'Sugar Labs'

- _includes/footer.html
- css/airspace.css
- index.html
Fixes: #358 
Removed the jquery function and extra CSS and style classes in the same section `#slider`
* removed `showSlides` jquery from `footer.html` 
* removed used .mySlides class css from `airspace.css` as mentioned in jquery and no more required
* removed unused class from 'section' which uses showSlides from index.html i.e. `#slider`
> fixed mySlides error

- _includes/footer.html
- fix broken link to IRC Channel in footer.html
> master: update IRC channel link

- _includes/footer.html
- booting-soas.html
- index.html
It was decommissioned many years ago.
> Drop socialhelp

- _includes/footer.html
- css/airspace.css
- css/ion_icon_customization.scss
@Jyoti28Dhikale please review.
Part of a fix to https://github.com/sugarlabs/www-sugarlabs/issues/345
> Remove sidebar social media icons

- css/ion_icon_customization.scss
Social icons look like this now. Resolves #392
> Changed social icons. Resolves issue #392

- _includes/footer.html
- more.html
This has copyedits, suggestions, and comments. The comments are in the HTML itself.
This needs review before publishing.
I have even more suggestions, but I'm trying to just make incremental improvements until we have a chance to agree upon some terminology and a styleguide.
> Copyedits more page

- about-us.html
Addresses issue #418 (in a somewhat clumsy way)
> Comment out local labs section (#418)

- _includes/footer.html
> Update footer to include events page

- _drafts/Sugar-Labs-announces-nonprofit-status-new-executive-director.md
You can test the draft by running `bundle exec jekyll serve --drafts`
Once we get it the way we want it, we copy it over with the YYYY-MM-DD-name.md naming convention; and, then, it should automagically create the html.
> Add a draft of an announcement

- contact-us.html
This updates the contact info page.
The formatting for the address is taken from https://scanmailboxes.com/support/docs/some-of-the-sender-or-the-vendor-will-not-recognize-my-new-scan-mailboxes-address-due-to-their-automatic-verification-system-what-should-i-do/
Our PMB at that address is: 1271
> Update contact info

- _includes/footer.html
- css/airspace.css
Fixes #439
PS: Red dashed line in dev mode only. Disappears in production
PS: Red dashed line in dev mode only. Disappears in production
> Adjusted footer for mobile visibility

- README.md
> Updated README on adding a new icon

- README.md
If there is a mailchimp account, please let me know.
> I don't believe we have Mailchimp integration, so I'm removing it

- js/main.js
- press.html
I have made the changes
Vedio:
https://github.com/user-attachments/assets/45ba62a7-2b59-423e-956c-6dac6ac70921
> fixex #456 Beautify /press/ and figure out how to limit to show only the last 10.

- sugarizer.html
This adds information on the various ways you can try Sugarizer, along with links and a few different reasons you might try any one of these options.
> Update Sugarizer page with all the different ways to try it

- contact-us.html
fixes #494 
@pikurasa please review.
> fixes #494 Add nifty icons to our contact-us list

- develop.html
fixes #493
@pikurasa please review.
> fixes #493 Add nifty icons to our list on Developers

- index.html
Fixes #492
https://github.com/user-attachments/assets/c5381d25-cd1d-4672-a30e-1fe6437b4b7c
> fix: added css property for better link visibility

- css/airspace.css
- index.html
**Description:**
- Added background for better visual appeal.
- Fixed typos: "reoccuring" → "recurring" and "tax-deductable" → "tax-deductible."
- Combined link and button redirecting to the same page into one link.
- Replaced image button with an actual `<button>` tag. 
Please review and provide feedback if needed. Here's before after update:
> feat: redesign donation section

- _includes/nav.html
- css/airspace.css
Fixes #478 
Vedio:
https://github.com/user-attachments/assets/ed165c3e-bba5-43ba-a651-cdb8acde5336
@pikurasa please refresh the page by clicking the sugarlabs logo after changing the dimension while testing.
> Fixes #478 Navbar is not rendering on mobile

- css/airspace.css
- index.html
- js/main.js
now when the user scroll down to the sugar by number part of the home page the animation starts after scrolling and create a beautiful counting animation 
[Screen Recording 2024-10-22 at 6.53.43 PM.zip](https://github.com/user-attachments/files/17477074/Screen.Recording.2024-10-22.at.6.53.43.PM.zip)
before this there is a static view of numbers in the home page
> Creating a proper number counting animation for the Sugar Labs website home page 

- css/custom.css
- music-blocks.html
**Allows user to play and view videos on te MB page directly
**Also added a link with MB youtube Playlist.
After :
> Adding new section named reference video in MB page

- css/airspace.css
> fix: remove extra dropdown icon

- _includes/about_sugar_labs.html
- _posts/2024-05-08-Sugar-Labs-announces-nonprofit-status-new-executive-director.md
Fixes #534
by adding a reusable component to the _includes folder for easier updates in one place.
> Added "About Sugar Labs" boilerplate to _includes

- _layouts/post.html
fixes #537 
@pikurasa I tried to beautify posts, this is how it looks.
Vedio:
https://github.com/user-attachments/assets/d33ceca8-22c5-48a4-b905-c99860f6c941
> Fixes #537 beautify _posts

- _layouts/base.html
fixes #521 
@pikurasa please review.
https://github.com/user-attachments/assets/2b285665-1a8a-4638-95be-24b4c6c29903
> fixes #521 Carousels

- css/airspace.css
- css/custom.css
Fixes: Solved the alignment issue of the icons in contact us Page, Minor changes. 
Before: 
After:
> solve the alignment issue of icon in contact us page

- _includes/nav.html
- css/custom.css
@pikurasa since the current position of donation banner is causing navbar to break, I have changed the position of donation banner.
This is how it looks now:
I'll hope it's an improvement.
> Change the positon of donation banner

- js/custom.js
@pikurasa updated number counter please review
> Updating number counter with commas 

- _posts/2024-12-29-sweet-spot-002.md
- css/custom.css
- Fix image rendering and bullet point display issues in the posts.
- Fixes: #622
- Made images responsive by adding max-width: 100%.
- Updated list styles to restore bullet points
- Validated markdown formatting to ensure proper rendering in Jekyll.
- Build the site locally with jekyll serve and verify image and list rendering.
- Check bullet points and image scaling on mobile and desktop views.
> Fix image scaling and restore list rendering in blog posts

- booting-soas.html
- index.html
https://github.com/user-attachments/assets/ae9574b5-9136-438b-8e2d-173cbd36ae6d
(ps: ignore the video quality)
Solves: #641
> Carousel added for booting soas steps

- community-news.html
- index.html
**Before**:
**After**:
Mobile View:
Desktop View:
**Key Changes:**
- Used flex box and centred all the content 
- Used form-control and btn classes of bootstrap for styling
- **Note:** The change is column width in community-news.html was done as the column width was too big and the input field was looking very large, that is changed col-md-12 to col-md-8
> Fixes #625, Improve styling of newsletter signup form on homepage and community-news page

- leadership.html
This PR updates the bio of Board of Directors for the 2025-26 cycle.
> Update leadership page

- _includes/nav.html
- product.html
- products.html
- sitemap.txt
@pikurasa please test to make sure that /product and /products redirect to same page that is /products,
and please let me know whether we want to go forward with this approach.
> Redirect /product to /products

- _posts/2024-05-01-Sugar-Labs-receives-eleven-contributor-projects-for-GSoC-2024.md
…and GSoC" and Table in Press Release Section of news section #659 .
> Fixes #659 Lack of Gap Between

- css/custom.css
- index.html
This PR introduces several improvements to the styling of the Testimonial section to create a more engaging and visually appealing user experience. The changes include adjustments to layout, typography, image styling, and interactive hover effects, ensuring a modern and responsive design.
1. **Testimonial Container:**
- Added padding and margin adjustments to improve spacing between elements.
- Introduced subtle rounded corners and a soft box-shadow effect for a more modern and polished look.
2. **Text Styling:**
- Improved typography by adjusting the font size, line-height, and weight for better readability and a more professional appearance.
- Added subtle text emphasis for reviewer names (bold or italicized), creating a more distinct visual hierarchy.
- 
3. **Quote Marks:**
- Enlarged …
> Enhanced Styling of Testimonials Section

- README.md
@pikurasa please review the instructions.
> Add instructions to give redirects

- _includes/donation_banner.html
- donate.html
- index.html
@pikurasa Can you please review it.
> update: donation link to every.org from paypal

- _layouts/base.html
@pikurasa Can you please review it?
> set carousel autoPlay to false 
